### ISSUE TITLE
No Bottle Support

### ISSUE THREAD

**Issue by MortenDeloke** [cScotPlay/Rusticated#1]
When you use the brewing system, you can´t put liquide in or take out of the fluid Barrel, you can´t put juice in the Brewing barrel either

**Comment by cScotPlay** [comment]
Updated in version 1.19.2-2.0.2.  Still need to update the 1.18 version.  Thanks for pointing this out.

**Comment by cScotPlay** [comment]
1.18.2 updated with 1.0.2.  Thanks again for reporting.
