### ISSUE TITLE
Crash when adding water to liquid barrel

### ISSUE THREAD

**Issue by VinceKezel** [cScotPlay/Rusticated#10]
When trying to add a bucket of water to the Liquid Barrel, the client crashes.

Whole game log attached. Crash happens on line 13043 ... hints at lines 13573 and 13596 and 13615
[barrel_crash.txt](https://github.com/cScotPlay/Rusticated/files/10842323/barrel_crash.txt)

Minecraft 1.19.2
Fabric 0.14.14
Rusticated 2.0.5
(lots of mods added in)

**Comment by VinceKezel** [comment]
Today, the client crashed when jumping on the grapes in the crushing tub.

**Comment by cScotPlay** [comment]
Thanks for identifying this.  The issue lies with the addition of Sodium.  Add Indium and this will fix the issue.  Future version has a warning screen that will identify this issue.

**Comment by cScotPlay** [comment]
Issue fixed in version 2.0.6
