### ISSUE TITLE
Crash with Sodium.

### ISSUE THREAD

**Issue by AnAwesomGuy** [cScotPlay/Rusticated#12]
[crash-2023-03-14_21.52.49-client.txt](https://github.com/cScotPlay/Rusticated/files/10969405/crash-2023-03-14_21.52.49-client.txt)
crashes with just jei, fabric api, sodium, and rusticated

**Comment by AnAwesomGuy** [comment]
is it ok if i make a list of enhancements/bugs with the crushing tub here?
kinda like #4

**Comment by cScotPlay** [comment]
Yes please do.  Working on getting a forge version pulled together also and will incorporate into it. Thanks

**Comment by AnAwesomGuy** [comment]
1. the fluids dont have any viscosity and also turns grass into dirt when placed on grass
2. fluids render weirdly (especially inside them)
3. no support for custom recipes
4. crushing tub can only hold 2 buckets of liquid
5. 1 berry -> 1 bucket of juice seems kinda op
6. if the crushing tub is full and you try to add more juice, it will delete the items when you keep crushing
7. same thing as above, but when you another item (e.g. you have sweet berry juice inside the tub and you try to crush iron berries)
8. no rei integration :(

**Comment by cScotPlay** [comment]
Alright, thank you.  Let me see what I can get after.

**Comment by cScotPlay** [comment]
Crashing with Sodium -- Thanks for identifying this. The issue lies with the addition of Sodium and the way I have fluid rendered. Add Indium and this will fix the issue. Future version has a warning screen that will identify this issue.  Continuing on the rest of the list.

**Comment by cScotPlay** [comment]
Updates to your request -- Currently only tested in the 1.19 version.  I see that your issues stem from the 1.18 version

1. the fluids dont have any viscosity and also turns grass into dirt when placed on grass (_Added fluid tags to act as water_)
2. fluids render weirdly (especially inside them) (_Fixed with addition of Fluid Tags_)
3. no support for custom recipes (_You can added custom JSON files that mimic the one already created for your custom recipes_ )
4. crushing tub can only hold 2 buckets of liquid (_Unable to actually replicate this.  They are set to hold 8 buckets_)
5. 1 berry -> 1 bucket of juice seems kinda op (_Again unable to replicate this Each berry will only give about a half a bucket.  To fill you will use 16 items_)
6. if the crushing tub is full and you try to add more juice, it will delete the items when you keep crushing  (_Not and issue in the current version_)
7. same thing as above, but when you another item (e.g. you have sweet berry juice inside the tub and you try to crush iron berries)
8. no rei integration :(  (_Added REI integration_)

Again thanks for all the improvements.  I know that these are all for the 1.19 version and I may get a chance to check up on the 1.18 but for now I really want to get the 1.19 version stable.  Thanks.

**Comment by cScotPlay** [comment]
Issue fixed in version 2.0.6
