### ISSUE TITLE
[BUG] Liquid Barrel Fluid Duplication & Bucket Stack Deletion

### ISSUE THREAD

**Issue by EpicGazel** [cScotPlay/Rusticated#14]
**Version**
v2.0.5-fabric, 1.19.2

**Issue**
A liquid barrel will hold 7 buckets if placed in manually, 1 bucket = 1/7th full. However, when fluid is piped in, the liquid barrel will completely fill from 99 MB. Thus, 1 bucket in ~=  70 buckets out. This works with lava as well as water.

If a bucket stack is used to extract fluids from the liquid barrel, the entire stack is consumed and only 1 bucket is returned. Thus, any extra buckets are deleted.

**Video Demonstration**
https://user-images.githubusercontent.com/20029624/234747536-62347afe-8cfd-4a1d-ac58-5037fde0ff85.mp4

**Comment by cScotPlay** [comment]
Thanks for posting this issues.  Fixed in upcoming update.

**Comment by cScotPlay** [comment]
At least the empty bucket stack and only holding 7 buckets of fluid

**Comment by cScotPlay** [comment]
Issue fixed in version 2.0.6
