### ISSUE TITLE
[Fabric 1.19.2] Issues, Enhancements and Other stuff

### ISSUE THREAD

**Issue by kingkuys2123** [cScotPlay/Rusticated#4]
## ✔ 2 Guidebooks 
Patchouli generate it's own Guidebook for Rusticated when installed
I made a PR that fixes this https://github.com/cScotPlay/Rusticated/pull/3/commits/a36ccd37772697f2645dc0c3185bd9f28362894b
![image](https://user-images.githubusercontent.com/114457180/214224790-7b5bbde0-8267-4b3f-a9f2-3d6340a4d34b.png)
## ✔ Guidebook's Resources
I suggest the guidebook's patchouli resources should be in the `assets` folder for easy localization and in favor of modpack creators that wants to edit some contents in the mod and also in the guidebook.🙂(Guidebooks can't be edited through datapacks) For example, Botania, it's guidebook's resources are located in it's `assets` folder. I can make a PR for this, it's quite easy actually. You just add `"use_resource_pack": true` inside the `data\rusticated\patchouli_books\rusticated_catalog\book.json` file and move the `data\rusticated\patchouli_books\rusticated_catalog\en_us` folder to the `assets\rusticated\patchouli_books\rusticated_catalog` folder
## ✔ Jars
Typo in the Jars guidebook page and also **Jars** hold fluids. 

Here's the revision:
`Jars are a decorative liquid storage option. Fired Jars hold 4 buckets of a single liquid, while the Glazed Jars hold 8 buckets. Like Pots, Jars also keep their inventory when broken.`

![image](https://user-images.githubusercontent.com/114457180/214230212-731350de-4ccf-4839-80da-d0a398c8a83b.png) 
![2023-01-24_15 04 57](https://user-images.githubusercontent.com/114457180/214231702-c44cb5f1-7b76-43c6-a848-f89a502d50a4.png)
## ✔ Missing Names
Made a PR that fixes this https://github.com/cScotPlay/Rusticated/pull/3/commits/6a920bd8e7b802000da50a486a7a3d0e2f0c82d2
![asdsad](https://user-images.githubusercontent.com/114457180/214224575-0f00b36b-31db-4c05-8bf8-3687ecb98dd6.png)
## ✔Crushing Tubs
When you place a crushable item (eg. apples, olives, grapes) in a Crushing Tub and get the item back, the crushing tub still renders the item on top of it
## ✔ Block Items
The following should not be registered as items (they show up in REI), You can register them with [`registerHerbs()`](https://github.com/cScotPlay/Rusticated/blob/e19c932c3ae0a1ff8839a57ed95cf3596ee1cbfd/src/main/java/net/mcs3/rusticated/init/ModBlocks.java) instead because that method only register them as blocks only and also maybe rename the method to `registerBlocks()`? (unless it's intentional🙂)
- **Grape Leaves**
- **Tied Stake**
- **Grape Stem**
- **Potted Olive Sapling**
- **Potted Ironwood Sapling**
## ✔ Loot Tables
- Missing **Grape Leaves**  loot table (they should drop ropes since they were attached to it and maybe grape seeds with a low chance)
- Missing **Potted Olive Sapling** loot table
- Missing **Potted Ironwood Sapling** loot table
## Tags
- **Jars and Urns** should be in `minecraft:mineable/pickaxe` **block tag** so they can be mined faster with pickaxes (unless this is intentional🙂)
- **Potted Saplings** should be in `minecraft:flower_pots` **block tag**
- **Leaves** should be in `minecraft:mineable/hoe` block tag , like the vanilla ones
- remove **Grape Leaves** from `minecraft:mineable/pickaxe`
- **Grape Stem** and **Grape Leaves** should be in `minecraft:crops` **block tag** and `minecraft:bee_growables` **block tag** like any other vanilla crops
- **Herbs except the mushrooms and root** should also be in `minecraft:bee_growables` **block tag** like sweet berry bushes, the bees would pollinate the herbs which increases the herbs' growth rate and then produces honeys to their hives when they return to it.
## ✔ Ropes & Grape Leaves
I suggest [Ropes](https://github.com/cScotPlay/Rusticated/blob/e19c932c3ae0a1ff8839a57ed95cf3596ee1cbfd/src/main/java/net/mcs3/rusticated/world/level/block/RopeBlock.java) should have the same block strength/resistance as Carpets `.strength(0.1F)` and remove `.instabreak()`, and [Grape Leaves](https://github.com/cScotPlay/Rusticated/blob/e19c932c3ae0a1ff8839a57ed95cf3596ee1cbfd/src/main/java/net/mcs3/rusticated/world/level/block/crop/GrapeLeavesBlock.java) should have the same block strength/resistance as Vanilla Leaves `.strength(0.2F)`, so they can't be mined instantly and prevent accidental breakage.... Then Ropes should be mined faster/instantly with Shears and Grape Leaves with Hoes/Shears
## ✔ Liquid Barrels
**Liquid Barrel** can't be obtained when mined (You prolly have a way to solve this in order to retain it's stored fluid nbt)

**Comment by cScotPlay** [comment]
Thanks for helping identify these issues.  I'll get after updating them!

**Comment by kingkuys2123** [comment]
No biggie! 😄

**Comment by cScotPlay** [comment]
Version *.0.3 contains fixes down to the Crushing Tubs.  Will continue to work.

**Comment by cScotPlay** [comment]
Version 0.4 fixes 

- Block Items (Block Items are not registered and no longer show in JEI)
- Loot Tables (Added for Grape Leaves and Potted Saplings)
- Ropes and Grapes (Updated as recommended didn't fix shears on Rope still looking at)
- Liquid Barrels (Now drop an item and hold their fluids)

From what I can tell the last thing is the Tags and get to them here soon.

**Comment by cScotPlay** [comment]
Version 0.5 fixes
-Fixed crafting recipe for ironwood and olive planks
-Added Tags to update the following:
  - mineable w/ pickaxe to Jars and Pots
  - flower pots to Potted Sapling Blocks
  - mineable w/ hoe to Leaves
  - crops tag to Grape Stem and Grape Leaves
  - bee growable tag to all Herbs and Grape Blocks
  
...and with that, I think that closes us out here.  Thanks for the assist.  If you see anything else, please let me know.
