### ISSUE TITLE
[1.19.2] Possible issue with sugarcane

### ISSUE THREAD

**Issue by Stopcode7e** [cScotPlay/Rusticated#5]
I noticed that I am unable to place sugarcane on any block other than Fertilized Soil. Is this an intended feature or should I still be able to plant sugarcane on dirt or sand that is adjacent to a water source block?

**Comment by angelpuppy** [comment]
ive also noticed this!

**Comment by cScotPlay** [comment]
ah yea that may be an issue on my side.  Let me take a look.  Thank you for identifying this.

**Comment by cScotPlay** [comment]
Fixed in the 2.0.3 version.  Please let me know if you have any additional issues.
