### ISSUE TITLE
[Suggestion] Farmers Delight and Let’s Do Wine compat

### ISSUE THREAD

**Issue by Sunconure11** [cScotPlay/Rusticated#6]
These two mods are practically begging for some compat with this mod.

Overweight Farming would also fit

**Comment by Sunconure11** [comment]
On top of this, there is a farmers delight addon that adds brewing

https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin-fabric

**Comment by cScotPlay** [comment]
Yea I'll add that to the list to look into. Thanks for the suggestion.

**Comment by Sunconure11** [comment]
How would you handle overlap in crops?

Also, another suggestion for compat is Dehydration.

**Comment by cScotPlay** [comment]
I probably won't add this enhancement any time soon.  May revisit in future versions.
