### ISSUE TITLE
Horsetail giving Wind Thistle

### ISSUE THREAD

**Issue by EmSalce** [cScotPlay/Rusticated#7]
When breaking horsetail flowers it gives you wind thistle instead :(

**Comment by EmSalce** [comment]
And Wind Thistle doesn't drop anything. Fabric 1.19.2, Rusticated v.2.0.3

**Comment by cScotPlay** [comment]
Thank you for reporting.  I'm in the process of working an update and will add this as something that needs fixing.

**Comment by cScotPlay** [comment]
Fixed in version 2.0.4.  Thanks again for highlighting this.
